# ==============================
# Aplicación
# ==============================
spring.application.name=ColegioOSSBackend01
server.port=8080

# ==============================
# Datasource - PostgreSQL
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/colegio_oss_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# Inicialización de datos (data.sql) - Parte 2 (pendiente crear el archivo)
# ==============================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ==============================
# JWT - Parte 6 (pendiente de implementar, dejamos las claves ya definidas)
# ==============================
app.jwt.secret=CAMBIAR_ESTE_SECRETO_POR_UNO_SEGURO_EN_PRODUCCION
app.jwt.access-token-expiration-ms=300000
#app.jwt.access-token-expiration-ms=10000
app.jwt.refresh-token-expiration-ms=604800000

# ==============================
# Swagger / OpenAPI - Parte 9 (pendiente de configurar el bean, pero property base)
# ==============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ==============================
# Logging
# ==============================
logging.level.org.springframework.security=INFO
logging.level.upc.colegioossbackend01=DEBUG

# ==============================
# Jackson - Serialización JSON
# ==============================
spring.jackson.default-property-inclusion=non_null

# ==============================
# Correo - Gmail SMTP
# ==============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:cruzrios4634@gmail.com}
spring.mail.password=${MAIL_PASSWORD:hirvfzxvlsrdppnb}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==============================
# Frontend - URL para enlace de recuperación
# ==============================
app.frontend.reset-password-url=${FRONTEND_RESET_URL:http://localhost:3000/reset-password}